server:
  port: 5001
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 2
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

netty:
  port: 3000

spring:
  application:
    name: smart-centeen
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lumia.live:3306/smartcanteen?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: ${spring.application.name}
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 1000MB
  messages:
    basename: messages
    encoding: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    password: 1qaz@WSX
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: 10000
        min-idle: 2
        time-between-eviction-runs: 3000
    host: lumia.live
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
    defaultEnumTypeHandler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  check-config-location: true
  global-config:
    db-config:
      logicDeleteValue: 1
      logic-not-delete-value: 0
    banner: false
  mapper-locations: classpath:/mapper/*.xml

logging:
  path: /usr/local/logs
